#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICDDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SICD")]
	public partial class SICDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SICDDataContext() : 
				base(global::SICDDAL.Properties.Settings.Default.SICDConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SICDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SICDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SICDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SICDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExternalInjurySelectSingle")]
		public ISingleResult<ExternalInjurySelectSingleResult> ExternalInjurySelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cause", DbType="VarChar(200)")] string cause)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cause);
			return ((ISingleResult<ExternalInjurySelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiseaseInjurySelectSingle")]
		public ISingleResult<DiseaseInjurySelectSingleResult> DiseaseInjurySelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiagnosisTerm", DbType="VarChar(200)")] string diagnosisTerm)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagnosisTerm);
			return ((ISingleResult<DiseaseInjurySelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DrugChemicalSelectSingle")]
		public ISingleResult<DrugChemicalSelectSingleResult> DrugChemicalSelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product", DbType="VarChar(200)")] string product)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), product);
			return ((ISingleResult<DrugChemicalSelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExternalCauseSelect")]
		public ISingleResult<ExternalCauseSelectResult> ExternalCauseSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cause", DbType="VarChar(200)")] string cause, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cause, flag);
			return ((ISingleResult<ExternalCauseSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CancerTumorSelectSingle")]
		public ISingleResult<CancerTumorSelectSingleResult> CancerTumorSelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords);
			return ((ISingleResult<CancerTumorSelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LandTransportSelectSingle")]
		public ISingleResult<LandTransportSelectSingleResult> LandTransportSelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword1", DbType="VarChar(200)")] string keyword1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword1);
			return ((ISingleResult<LandTransportSelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LandTransportSelect")]
		public ISingleResult<LandTransportSelectResult> LandTransportSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords, flag);
			return ((ISingleResult<LandTransportSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CancerTumorSelect")]
		public ISingleResult<CancerTumorSelectResult> CancerTumorSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords, flag);
			return ((ISingleResult<CancerTumorSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiseaseInjurySelect")]
		public ISingleResult<DiseaseInjurySelectResult> DiseaseInjurySelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiagnosisTerm", DbType="VarChar(200)")] string diagnosisTerm, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagnosisTerm, flag);
			return ((ISingleResult<DiseaseInjurySelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DrugChemicalSelect")]
		public ISingleResult<DrugChemicalSelectResult> DrugChemicalSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product", DbType="VarChar(200)")] string product, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), product, flag);
			return ((ISingleResult<DrugChemicalSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearch301Select")]
		public ISingleResult<QuickSearch301SelectResult> QuickSearch301Select([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(255)")] string keywords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords, flag);
			return ((ISingleResult<QuickSearch301SelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearch301SelectSingle")]
		public ISingleResult<QuickSearch301SelectSingleResult> QuickSearch301SelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords);
			return ((ISingleResult<QuickSearch301SelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearchBjSelect")]
		public ISingleResult<QuickSearchBjSelectResult> QuickSearchBjSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(255)")] string keywords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords, flag);
			return ((ISingleResult<QuickSearchBjSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearchBjSelectSingle")]
		public ISingleResult<QuickSearchBjSelectSingleResult> QuickSearchBjSelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords);
			return ((ISingleResult<QuickSearchBjSelectSingleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearchWsbSelect")]
		public ISingleResult<QuickSearchWsbSelectResult> QuickSearchWsbSelect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(255)")] string keywords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords, flag);
			return ((ISingleResult<QuickSearchWsbSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QuickSearchWsbSelectSingle")]
		public ISingleResult<QuickSearchWsbSelectSingleResult> QuickSearchWsbSelectSingle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="VarChar(200)")] string keywords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywords);
			return ((ISingleResult<QuickSearchWsbSelectSingleResult>)(result.ReturnValue));
		}
	}
	
	public partial class ExternalInjurySelectSingleResult
	{
		
		private string _Cause;
		
		private string _ICD10;
		
		public ExternalInjurySelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cause", DbType="VarChar(8000)")]
		public string Cause
		{
			get
			{
				return this._Cause;
			}
			set
			{
				if ((this._Cause != value))
				{
					this._Cause = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICD10", DbType="VarChar(255)")]
		public string ICD10
		{
			get
			{
				return this._ICD10;
			}
			set
			{
				if ((this._ICD10 != value))
				{
					this._ICD10 = value;
				}
			}
		}
	}
	
	public partial class DiseaseInjurySelectSingleResult
	{
		
		private string _DiagnosisTerm;
		
		private string _General;
		
		private string _Congenital;
		
		private string _PerinatalNeonatal;
		
		private string _Pregnancy;
		
		private string _Childbirth;
		
		private string _Postpartum;
		
		public DiseaseInjurySelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosisTerm", DbType="VarChar(255)")]
		public string DiagnosisTerm
		{
			get
			{
				return this._DiagnosisTerm;
			}
			set
			{
				if ((this._DiagnosisTerm != value))
				{
					this._DiagnosisTerm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_General", DbType="VarChar(255)")]
		public string General
		{
			get
			{
				return this._General;
			}
			set
			{
				if ((this._General != value))
				{
					this._General = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Congenital", DbType="VarChar(255)")]
		public string Congenital
		{
			get
			{
				return this._Congenital;
			}
			set
			{
				if ((this._Congenital != value))
				{
					this._Congenital = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerinatalNeonatal", DbType="VarChar(255)")]
		public string PerinatalNeonatal
		{
			get
			{
				return this._PerinatalNeonatal;
			}
			set
			{
				if ((this._PerinatalNeonatal != value))
				{
					this._PerinatalNeonatal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pregnancy", DbType="VarChar(255)")]
		public string Pregnancy
		{
			get
			{
				return this._Pregnancy;
			}
			set
			{
				if ((this._Pregnancy != value))
				{
					this._Pregnancy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Childbirth", DbType="VarChar(255)")]
		public string Childbirth
		{
			get
			{
				return this._Childbirth;
			}
			set
			{
				if ((this._Childbirth != value))
				{
					this._Childbirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postpartum", DbType="VarChar(255)")]
		public string Postpartum
		{
			get
			{
				return this._Postpartum;
			}
			set
			{
				if ((this._Postpartum != value))
				{
					this._Postpartum = value;
				}
			}
		}
	}
	
	public partial class DrugChemicalSelectSingleResult
	{
		
		private string _DrugOrChemicalProduct;
		
		private string _Poisoning;
		
		private string _Accident;
		
		private string _IntentionalSelfHarm;
		
		private string _UnknownIntent;
		
		private string _AdvesreEffect;
		
		public DrugChemicalSelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugOrChemicalProduct", DbType="VarChar(255)")]
		public string DrugOrChemicalProduct
		{
			get
			{
				return this._DrugOrChemicalProduct;
			}
			set
			{
				if ((this._DrugOrChemicalProduct != value))
				{
					this._DrugOrChemicalProduct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poisoning", DbType="VarChar(255)")]
		public string Poisoning
		{
			get
			{
				return this._Poisoning;
			}
			set
			{
				if ((this._Poisoning != value))
				{
					this._Poisoning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accident", DbType="VarChar(255)")]
		public string Accident
		{
			get
			{
				return this._Accident;
			}
			set
			{
				if ((this._Accident != value))
				{
					this._Accident = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentionalSelfHarm", DbType="VarChar(255)")]
		public string IntentionalSelfHarm
		{
			get
			{
				return this._IntentionalSelfHarm;
			}
			set
			{
				if ((this._IntentionalSelfHarm != value))
				{
					this._IntentionalSelfHarm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnknownIntent", DbType="VarChar(255)")]
		public string UnknownIntent
		{
			get
			{
				return this._UnknownIntent;
			}
			set
			{
				if ((this._UnknownIntent != value))
				{
					this._UnknownIntent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvesreEffect", DbType="VarChar(255)")]
		public string AdvesreEffect
		{
			get
			{
				return this._AdvesreEffect;
			}
			set
			{
				if ((this._AdvesreEffect != value))
				{
					this._AdvesreEffect = value;
				}
			}
		}
	}
	
	public partial class ExternalCauseSelectResult
	{
		
		private string _Cause;
		
		public ExternalCauseSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cause", DbType="VarChar(8000)")]
		public string Cause
		{
			get
			{
				return this._Cause;
			}
			set
			{
				if ((this._Cause != value))
				{
					this._Cause = value;
				}
			}
		}
	}
	
	public partial class CancerTumorSelectSingleResult
	{
		
		private string _keyword;
		
		private string _Primary;
		
		private string _Secondary;
		
		private string _insitu;
		
		private string _benign;
		
		private string _tumor;
		
		private string _Remark;
		
		public CancerTumorSelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this._keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary]", Storage="_Primary", DbType="VarChar(255)")]
		public string Primary
		{
			get
			{
				return this._Primary;
			}
			set
			{
				if ((this._Primary != value))
				{
					this._Primary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secondary", DbType="VarChar(255)")]
		public string Secondary
		{
			get
			{
				return this._Secondary;
			}
			set
			{
				if ((this._Secondary != value))
				{
					this._Secondary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insitu", DbType="VarChar(255)")]
		public string insitu
		{
			get
			{
				return this._insitu;
			}
			set
			{
				if ((this._insitu != value))
				{
					this._insitu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_benign", DbType="VarChar(255)")]
		public string benign
		{
			get
			{
				return this._benign;
			}
			set
			{
				if ((this._benign != value))
				{
					this._benign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tumor", DbType="VarChar(255)")]
		public string tumor
		{
			get
			{
				return this._tumor;
			}
			set
			{
				if ((this._tumor != value))
				{
					this._tumor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(255)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class LandTransportSelectSingleResult
	{
		
		private string _Keyword1;
		
		private string _Keyword2;
		
		private string _Code;
		
		public LandTransportSelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword1", DbType="NVarChar(255)")]
		public string Keyword1
		{
			get
			{
				return this._Keyword1;
			}
			set
			{
				if ((this._Keyword1 != value))
				{
					this._Keyword1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword2", DbType="NVarChar(255)")]
		public string Keyword2
		{
			get
			{
				return this._Keyword2;
			}
			set
			{
				if ((this._Keyword2 != value))
				{
					this._Keyword2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(255)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
	}
	
	public partial class LandTransportSelectResult
	{
		
		private string _Keyword1;
		
		private string _Keyword2;
		
		public LandTransportSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword1", DbType="NVarChar(255)")]
		public string Keyword1
		{
			get
			{
				return this._Keyword1;
			}
			set
			{
				if ((this._Keyword1 != value))
				{
					this._Keyword1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword2", DbType="NVarChar(255)")]
		public string Keyword2
		{
			get
			{
				return this._Keyword2;
			}
			set
			{
				if ((this._Keyword2 != value))
				{
					this._Keyword2 = value;
				}
			}
		}
	}
	
	public partial class CancerTumorSelectResult
	{
		
		private string _keyword;
		
		public CancerTumorSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this._keyword = value;
				}
			}
		}
	}
	
	public partial class DiseaseInjurySelectResult
	{
		
		private string _DiagnosisTerm;
		
		public DiseaseInjurySelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosisTerm", DbType="VarChar(255)")]
		public string DiagnosisTerm
		{
			get
			{
				return this._DiagnosisTerm;
			}
			set
			{
				if ((this._DiagnosisTerm != value))
				{
					this._DiagnosisTerm = value;
				}
			}
		}
	}
	
	public partial class DrugChemicalSelectResult
	{
		
		private string _DrugOrChemicalProduct;
		
		public DrugChemicalSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugOrChemicalProduct", DbType="VarChar(255)")]
		public string DrugOrChemicalProduct
		{
			get
			{
				return this._DrugOrChemicalProduct;
			}
			set
			{
				if ((this._DrugOrChemicalProduct != value))
				{
					this._DrugOrChemicalProduct = value;
				}
			}
		}
	}
	
	public partial class QuickSearch301SelectResult
	{
		
		private string _term;
		
		public QuickSearch301SelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
	
	public partial class QuickSearch301SelectSingleResult
	{
		
		private string _icd_code;
		
		private string _Star_code;
		
		private string _term;
		
		public QuickSearch301SelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icd_code", DbType="NVarChar(255)")]
		public string icd_code
		{
			get
			{
				return this._icd_code;
			}
			set
			{
				if ((this._icd_code != value))
				{
					this._icd_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Star_code", DbType="NVarChar(255)")]
		public string Star_code
		{
			get
			{
				return this._Star_code;
			}
			set
			{
				if ((this._Star_code != value))
				{
					this._Star_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
	
	public partial class QuickSearchBjSelectResult
	{
		
		private string _term;
		
		public QuickSearchBjSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
	
	public partial class QuickSearchBjSelectSingleResult
	{
		
		private string _icd_code;
		
		private string _Star_code;
		
		private string _term;
		
		public QuickSearchBjSelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icd_code", DbType="NVarChar(255)")]
		public string icd_code
		{
			get
			{
				return this._icd_code;
			}
			set
			{
				if ((this._icd_code != value))
				{
					this._icd_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Star_code", DbType="NVarChar(255)")]
		public string Star_code
		{
			get
			{
				return this._Star_code;
			}
			set
			{
				if ((this._Star_code != value))
				{
					this._Star_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
	
	public partial class QuickSearchWsbSelectResult
	{
		
		private string _term;
		
		public QuickSearchWsbSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
	
	public partial class QuickSearchWsbSelectSingleResult
	{
		
		private string _icd_code;
		
		private string _Star_code;
		
		private string _term;
		
		public QuickSearchWsbSelectSingleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icd_code", DbType="NVarChar(10)")]
		public string icd_code
		{
			get
			{
				return this._icd_code;
			}
			set
			{
				if ((this._icd_code != value))
				{
					this._icd_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Star_code", DbType="NVarChar(10)")]
		public string Star_code
		{
			get
			{
				return this._Star_code;
			}
			set
			{
				if ((this._Star_code != value))
				{
					this._Star_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(255)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this._term = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
